cart/urls.py
# from django.urls import path
# from . import views
#
# app_name = 'cart'
# urlpatterns = [
#     path('add/<int:product_id>/', views.add_cart, name='add_cart'),
#     path('', views.cart_detail, name='cart_detail'),
#
# ]
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove')

]

ecommerce_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('shop/', include('shop_app.urls')),
                  path('search_app/', include('search_app.urls')),
                  path('cart/', include('cart.urls', namespace='cart')),

          ]    # ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.SearchResult, name='SearchResult'),

]

shop_app/urls.py
from . import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop_app'
urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),

]
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from shop_app.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.cart_id)

cart/views.py
# from django.shortcuts import render, redirect
# from shop_app.models import Product
# from .models import Cart, CartItem
# from django.core.exceptions import ObjectDoesNotExist
#
#
# def _cart_id(request):
#     cart = request.session.session_key
#     if not cart:
#         cart = request.session.create()
#     return cart
#
#
# def add_cart(request, product_id):
#     product = Product.objects.get(id=product_id)
#     try:
#         cart = Cart.objects.get(cart_id=_cart_id(request))
#     except Cart.DoesNotExist:
#         cart = Cart.objects.create(
#             cart_id=_cart_id(request)
#         )
#         cart.save()
#     try:
#         cart_item = CartItem.objects.get(product=product, cart=cart)
#         cart_item.quantity += 1
#         cart_item.save()
#     except CartItem.DoesNotExist:
#         cart_item = CartItem.objects.create(
#             product=product,
#             quantity=1,
#             cart=cart
#         )
#         cart_item.save()
#     return redirect('cart:cart_detail')
#
#
# def cart_detail(request, total=0, counter=0, cart_items=None):
#     try:
#         cart = Cart.objects.get(cart_id=_cart_id(request))
#         cart_items = CartItem.objects.filter(cart=cart, active=True)
#         for cart_item in cart_items:
#             total += (cart_item.product.price * cart_item.quantity)
#             counter += cart_item.quantity
#     except ObjectDoesNotExist:
#         pass
#     return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))
# # def cart_detail(request, total=0, counter=0):
# #     cart = Cart.objects.filter(cart_id=_cart_id(request)).first()
# #     if cart:
# #         cart_items = CartItem.objects.filter(cart=cart, active=True)
# #         for cart_item in cart_items:
# #             total += (cart_item.product.price * cart_item.quantity)
# #             counter += cart_item.quantity
# #     return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))
#
from django.shortcuts import render, redirect, get_object_or_404
from shop_app.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        cart_items = CartItem.objects.none()
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-2xUfoMRCCUm8jZV7TuXJhCfVdYZu2a22rVwG5r5M5H0jpybMZe93be1Z9O/nUb+nR8JMnvbHfBy62w+iQCYQWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static '/css/custom.css' %}">
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">-->

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{%block metadescription%}{% endblock %} ">
    <title>{%block title%}{% endblock %}</title>
</head>
<body>

<div>


{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<!--    <script src="{% static 'js/popper.min.js' %}"></script>-->
<!--    <script src="{% static 'js/bootstrap.min.js' %}"></script>-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We are providing a different varieties of collections for both men and women..........
{% endblock %}
{% block title %}
    Cart ABC PVT LTD
{% endblock %}
{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    YOUR CART IS EMPTY
                </h1>
                <br>
                <p class="text-center">
                    Please click  <a href="{% url 'shop_app:allProdCart' %}"> here </a> to continue shopping.
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    YOUR SHOPPING CART
                </h1>
                <br>
            </div>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                Your items
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="cart_item.product.get_absolute_url"><img src="{{ cart_item.product.image.url }}" alt="" height="150" width="200" class="float-left rounded custom_image"></a>
                                </td>
                                <td class="text-lef">
                                    {{ cart_item.product.name }}
                                    <br>
                                    SKU: {{ cart_item.product.id }}
                                    <br>
                                    Price: $ {{ cart_item.product.price }}
                                    <br>
                                    Qty: {{ cart_item.quantity }} x $ {{cart_item.product.price}}
                                </td>
                                <td>
                                    $ {{ cart_item.sub_total }}
                                </td>
                                {% if cart_item.quantity < cart_item.product.stock %}
                                    <td>
                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus-square custom_icon"></i></a>
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                                    </td>
                                {% else %}
                                    <td>
                                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th>
                                Checkout
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please review your shopping cart items before proceeding with the order payments.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                Your total is : <strong> {{ total }}</strong>

                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="mx-auto">

        <a href="{% url 'shop_app:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button"> Continue Shopping</a>
        <a href="{% url 'shop_app:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button2"> Make Payment </a>

    </div>
</div>

</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155}}
    {% else %}
        Welcome to ABC store where you can buys different items....
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} -ABC Store
    {% else %}
        See our New collections of -ABC Store
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                <p><!-- <a href="{% url 'shop_app:allProdCat' %}">Our Product collections</a> -->
                    <a href="{% url 'shop_app:product_by_category' category.slug %}">Our Product collections</a>
                </p>
            </div>
                </div>
        </div>
    {% endif %}

    <div class="mx_auto">
        {% if category %}
            <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
           </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{ category.name }}</h1>
        <p class="text-justify">{{ category.description }}</p>
    </div>
        {% else %}
            <div>
            <img class="my_image my_image_padding" src="{%static 'img/ban1.png'%} " alt="our products" >
            </div>

            <br>
            <div>
                <h1 class="text-center my_title">Our products Collections</h1>
                <p class="text-justify"> ABC is a state-of-the-art hypermarket that is designed to provide customers with an exceptional shopping experience. The store offers a vast range of products, including fresh produce, groceries, electronics, household items, and clothing, to name a few. The hypermarket is equipped with modern facilities and features, such as ample parking space, air conditioning, and comfortable seating areas for customers to relax and enjoy their shopping experience. ABC prides itself on providing excellent customer service, with friendly and knowledgeable staff on hand to assist customers with their queries and provide expert advice. With its comprehensive range of products and customer-centric approach, ABC is sure to become a popular destination for shoppers looking for convenience, quality, and value for money.</p>
            </div>
            {% endif %}



    <div class="container">
        <div class="row mx_auto">
            {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                    <div class="card text-center" style="min-width:18rem;">
                        <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" height="300" width="300"></a>
                        <div class="card-body" >
                            <h4>{{product.name}}</h4>
                            <p> {{product.description}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
            <br>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm" {% if products.number == pg%} active {% endif%}>{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <br>

    </div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center"> &copy ABC tech pvt ltd .All rights reserved</p>
</div>

templates/header.html
{% load static %}
<header>
  <center>
    <a href="{%url 'shop_app:allProdCat'%}"> <img src="{%static 'img/logo.png'%}"  alt="logimage" , height="100" ,width="100">
     </center>


</header>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> haiii....</h1>
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown if {% if 'shop_app' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shop_app:allProdCat' %}">All Products</a></li>
                 {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.description|truncatewords:155}}

{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} -ABC Store
    {% endif %}
{% endblock %}

{% block content %}


<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p>
            <a href="{% url 'shop_app:allProdCat' %}">Home</a>  | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}
        </p>
    </div>
</div>

<div class="container"></div>
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}" height="250" width="250">
        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product description</p>
            <p class="text-justify my_rod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href=" {% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}
        </div>
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        We are providing a different varieties of collections for both men and women..........
{% endblock %}
{% block title %}
        Search
{% endblock %}
{% block content %}
<div>
        <p class="text-center my_search_text">You have searched for: <b> "{{query}}"</b></p>
</div>

  <div class="container">
        <div class="row mx_auto">
            {% for product in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                    <div class="card text-center" style="min-width:18rem;">
                        <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" height="300" width="300"></a>
                        <div class="card-body" >
                            <h4>{{product.name}}</h4>
                            <p> {{product.description}}</p>
                        </div>
                    </div>
                </div>
                {% empty %}

                <div class="row mx-auto">
                        <p class="text-center my_search_text"> 0 result found</p>
                </div>
            {% endfor %}
        </div>
  </div>
{% endblock %}